# Generated by Django 2.1.7 on 2019-03-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d')),
                ('phone_number', models.CharField(default='XXXXXXXXXX', max_length=12)),
                ('org_name', models.CharField(default='organization name', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='qna_app.Staff'),
        ),
    ]
